import streamlit as st
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import spearmanr

# Try to import UMAP, fallback to PCA if missing
try:
    import umap
    USE_UMAP = True
except ImportError:
    from sklearn.decomposition import PCA
    USE_UMAP = False

# ----------------------------
# Streamlit page configuration
# ----------------------------
st.set_page_config(page_title="Alpha Model Dashboard", layout="wide")
st.title("📈 Tab 2 – Alpha Model Visualization")

# ----------------------------
# File paths
# ----------------------------
PRED_PATH = "data/processed/alpha_predictions.parquet"
IC_PATH = "data/processed/ic_results.parquet"
ATTN_PATH = "data/processed/graph_adj.npy"
EMB_PATH = "data/processed/node_embeddings.npy"
SECTOR_PATH = "data/raw/ticker_sector.csv"

# =========================================================
# 1️⃣ Predicted Alpha vs Daily IC
# =========================================================
st.header("1️⃣ Predicted Alpha vs Daily IC")

try:
    df_pred = pd.read_parquet(PRED_PATH)
    df_ic = pd.read_parquet(IC_PATH)

    st.write("**Predicted Alpha sample:**")
    st.dataframe(df_pred.head())
    st.write("**IC results sample:**")
    st.dataframe(df_ic.head())

    # Merge on 'date' only
    df = pd.merge(df_pred, df_ic, on='date', how='inner')

    fig1, ax1 = plt.subplots(figsize=(7, 5))
    sns.scatterplot(data=df, x='IC', y='alpha', alpha=0.6, ax=ax1)
    ax1.set_title("Predicted Alpha vs Daily Information Coefficient (IC)")
    ax1.set_xlabel("Daily IC")
    ax1.set_ylabel("Predicted Alpha")
    ax1.grid(True)
    st.pyplot(fig1)

except Exception as e:
    st.warning(f"⚠️ Could not generate scatter plot: {e}")

# =========================================================
# 2️⃣ Attention Heatmap (GNN Feature Importance)
# =========================================================
st.header("2️⃣ Attention Heatmap (GNN Feature Importance)")

try:
    attn = np.load(ATTN_PATH)
    df_attn = pd.DataFrame(attn)

    fig2, ax2 = plt.subplots(figsize=(10, 6))
    sns.heatmap(df_attn, cmap="YlGnBu", cbar=True, ax=ax2)
    ax2.set_title("GNN Feature Attention Heatmap")
    ax2.set_xlabel("Attention Head / Node")
    ax2.set_ylabel("Feature")
    st.pyplot(fig2)

except Exception as e:
    st.warning(f"⚠️ Could not generate attention heatmap: {e}")

# =========================================================
# 3️⃣ Node Embeddings (UMAP or PCA Projection)
# =========================================================
st.header("3️⃣ Node Embeddings (2D Projection)")

try:
    embeddings = np.load(EMB_PATH)
    df_sector = pd.read_csv(SECTOR_PATH)

    if USE_UMAP:
        reducer = umap.UMAP(random_state=42)
        emb_2d = reducer.fit_transform(embeddings)
        title_suffix = "UMAP"
    else:
        from sklearn.decomposition import PCA
        reducer = PCA(n_components=2)
        emb_2d = reducer.fit_transform(embeddings)
        title_suffix = "PCA (fallback)"

    df_plot = pd.DataFrame(emb_2d, columns=["Dim1", "Dim2"])
    df_plot["sector"] = df_sector["sector"].values[:len(df_plot)]

    fig3, ax3 = plt.subplots(figsize=(8, 6))
    sns.scatterplot(
        data=df_plot, x="Dim1", y="Dim2", hue="sector",
        palette="tab10", s=50, ax=ax3, alpha=0.8
    )
    ax3.set_title(f"Node Embeddings ({title_suffix} Projection)")
    ax3.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
    st.pyplot(fig3)

except Exception as e:
    st.warning(f"⚠️ Could not generate embedding plot: {e}")

# =========================================================
# Footer
# =========================================================
st.markdown("---")
st.caption("Generated by GPT-5 • Alpha Model Visualization Dashboard")
